### ISSUE TITLE
Removes uppercase letters which are not followed by a lowercase letter

### ISSUE THREAD

**Issue by coniel** [pedsmoreira/casex#1]
Thanks for creating this, it's been very handy!

I came across an unexpected result though. If the input string has uppercase letters which are not followed by a lowercase letter, they are not included in the output. For example, an input of `SubmitFormFAB` with a pattern of `caSe` results in an output of `submitForm`. An input of `SubmitForm F A B` also results in `submitForm`;

It works fine if the input string is in the form `SubmitForm f a b`, which I'm currently typing as a workaround.

**Comment by pedsmoreira** [comment]
Hey @coniel, thanks for the kind words :)

This is indeed a bug. I'm releasing a new version (1.0.0) that fixes this and add supports to numbers, such as in `SubmitForm2`.

Enjoy!

Ps.: I added a test case for your issue so it doesn't come back in the future :)
https://github.com/pedsmoreira/casex/blob/master/tests/nameCase.test.js#L40

**Comment by coniel** [comment]
Great! Thanks a lot!
